"""Add active status to User model

Revision ID: 59a85bf33c87
Revises: drop_distance_in_meters
Create Date: 2025-09-04 00:50:17.413690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59a85bf33c87'
down_revision = 'drop_distance_in_meters'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clock_session', schema=None) as batch_op:
        batch_op.drop_index('ux_clock_session_one_active_per_user', postgresql_where='((clock_out IS NULL) AND (is_active = true))')

    with op.batch_alter_table('device_log', schema=None) as batch_op:
        batch_op.drop_column('clock_in_accuracy')
        batch_op.drop_column('clock_in_longitude')
        batch_op.drop_column('clock_out_accuracy')
        batch_op.drop_column('clock_out_longitude')
        batch_op.drop_column('clock_out_latitude')
        batch_op.drop_column('clock_in_latitude')
        batch_op.drop_column('clock_in_distance_mi')
        batch_op.drop_column('clock_out_distance_mi')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('active')

    with op.batch_alter_table('device_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clock_out_distance_mi', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('clock_in_distance_mi', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('clock_in_latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('clock_out_latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('clock_out_longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('clock_out_accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('clock_in_longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('clock_in_accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    with op.batch_alter_table('clock_session', schema=None) as batch_op:
        batch_op.create_index('ux_clock_session_one_active_per_user', ['user_id'], unique=True, postgresql_where='((clock_out IS NULL) AND (is_active = true))')

    # ### end Alembic commands ###
