"""Add location tracking fields to ClockSession

Revision ID: add_location_tracking_fields
Revises: 7a6119aba375
Create Date: 2025-04-18 16:32:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_location_tracking_fields'
down_revision = '7a6119aba375'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clock_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clock_in_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('clock_in_longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('clock_in_accuracy', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('clock_in_distance_m', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('clock_out_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('clock_out_longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('clock_out_accuracy', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('clock_out_distance_m', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clock_session', schema=None) as batch_op:
        batch_op.drop_column('clock_out_distance_m')
        batch_op.drop_column('clock_out_accuracy')
        batch_op.drop_column('clock_out_longitude')
        batch_op.drop_column('clock_out_latitude')
        batch_op.drop_column('clock_in_distance_m')
        batch_op.drop_column('clock_in_accuracy')
        batch_op.drop_column('clock_in_longitude')
        batch_op.drop_column('clock_in_latitude')
    # ### end Alembic commands ###